knp_snappy:
    pdf:
        enabled:    true
        binary:     'C:\Users\user\wkhtmltopdf\bin\wkhtmltopdf.exe'
        options:    []
    image:
        enabled:    true
        binary:     'C:\Users\user\wkhtmltopdf\bin\wkhtmltoimage.exe'
        options:    []